### ISSUE TITLE
Install dfx version in dfx.json

### ISSUE THREAD

**Issue by bitdivine** [dfinity/setup-dfx#3]
# Motivation
A common case is going to be installing the `dfx` specified in `dfx.json`.

# Possible solutions

## Make it the Default?
We could, by default, install the `dfx` specified in `dfx.json`, if specified, else install the latest.

## Provide an Example?
We could keep the code as it is but provide an example for how to do this.  E.g.:
```
jobs:
  example-job:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Get dfx version
      id: version
      run: echo "dfx_version=$(jq -r .dfx dfx.json)" >> "$GITHUB_OUTPUT"
    - name: Install dfx
      uses: dfinity/setup-dfx@main
      with: 
        dfx-version: ${{ steps.version.outputs.dfx_version }}
    - name: Confirm successful installation
      run: dfx --version
```
Warning: The above is _completely_ untested!

# See also
For projects that specify a dfx version, there is [a GitHub workflow](https://github.com/dfinity/snsdemo/blob/main/.github/workflows/update-dfx.yml) that periodically checks for a newer `dfx` and, if it finds one, opens a PR updating dfx.  It is written for our specific requirements but it might be worth making a version suitable for public use.
