### ISSUE TITLE
Add option to setup system subnet

### ISSUE THREAD

**Issue by nathanosdev** [dfinity/setup-dfx#4]
I commonly find myself needing to setup a system subnet for DFX (for use with `dfx nns`). It would be nice to have that encapsulated inside this action. The step I use is this, it could easily be configured further to only run when an input variable `setupSystemSubnet` is set to `true`.

```yaml
    - name: Configure system subnet
      shell: bash
      run: |
        mkdir -p $HOME/.config/dfx
        cat <<EOF >$HOME/.config/dfx/networks.json
        {
          "local": {
            "bind": "127.0.0.1:8080",
            "type": "ephemeral",
            "replica": {
              "subnet_type": "system"
            }
          }
        }
        EOF
```

Full example of the action I use is [here](https://github.com/TaggrNetwork/taggr/blob/main/.github/actions/setup-dfx/action.yml).
